version: "3"
networks:
  web:
    external: true
services:
  epping_bottle:
    build: bottle
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:epping.dev.urbanobservatory.ac.uk"